#!/usr/bin/env node

const http = require("http");
const https = require("https");
const fs = require("fs");

const common = require("./src/common");


let config = {};

if(fs.existsSync("config.json")) {
	config = JSON.parse(fs.readFileSync("config.json"));
} else {
	config.services = JSON.parse(fs.readFileSync("src/services.json"));
}

function updateConfig() {
	https.get(common.SERVICES_URL, res => {
		let body = "";
		res.on("data", data => {
			body += data;
		});
		res.on("end", () => {
			config = {
				"services": JSON.parse(body),
				"lastUpdated": Date.now()
			};
			fs.writeFileSync("config.json", JSON.stringify(config));
			console.log("service list updated successfully!");
		});
	});
}

common.startAutoUpdate(config.lastUpdated, nextUpdateTimestamp => {
	setTimeout(() => {
		updateConfig();
		setInterval(updateConfig, common.UPDATE_INTERVAL_MINUTES * 1000 * 60);
	}, nextUpdateTimestamp - Date.now());
});

http.createServer((req, res) => {

	res.setHeader("Content-Type", "text/plain");

	let oldUrl = req.url.slice(1);
	let url;
	try {
		url = new URL(oldUrl);
	} catch(error) {
		try {
			oldUrl = "https://" + oldUrl;
			url = new URL(oldUrl);
		} catch(error) {
			res.writeHead(400).end(JSON.stringify(error));
			return;
		}
	}

	for(let service of config.services) {
		for(let transformation of service.transformations) {
			if(url.host.endsWith(new URL("https://" + transformation.domain).host)) {
				let instances = common.flattenInstanceList(service.instances);
				let newUrl = common.transformUrl(oldUrl, instances, service.transformations);
				res.writeHead(302, {Location: newUrl}).end();
				console.log(newUrl);
				return;
			}
		}
	}

	res.writeHead(404).end(oldUrl + " not found");
}).listen(8080);
